server:
  port: 8080
  servlet:
    context-path: /
spring:
  application:
    name: hpsys
  # 数据源
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/hp?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: root
    password: 123456
    hikari:
      #连接池名
      pool-name: DataHikariCP
      # 最小空闲连接数
      minimum-idle: 5
      # 空闲连接存活最大时间，默认是600000(10分钟)
      idle-timeout: 180000
      # 最大的俩技术，默认是10
      maximum-pool-size: 10
      # 从连接池返回的连接自动提交
      auto-commit: true
      # 连接最大存活时间，0表示永久存活，默认是30分钟 (1800000)
      max-lifetime: 1800000
      # 连接超时时间，默认就是30000（30秒）
      connection-timeout: 30000
      # 测试连接是否可用的查询语句
      connection-test-query: select 1
  # freemarker设置
  freemarker:
    suffix: .ftl
    content-type: text/html
    charset: UTF-8
    template-loader-path: classpath:/views/
    request-context-attribute: request
    settings:
      number_format: 0.##
  activiti:
    ## 数据库更新策略
    ## flase:默认值。activiti在启动时，会对比数据库表中保存的版本，如果没有表或者版本不匹配，将抛出异常。（生产环境常用）
    ## true:  activiti会对数据库中所有表进行更新操作。如果表不存在，则自动创建。（开发时常用）
    ## create_drop：在activiti启动时创建表，在关闭时删除表（必须手动关闭引擎，才能删除表）。（单元测试常用）
    ## drop-create： 在activiti启动时删除原来的旧表，然后在创建新表（不需要手动关闭引擎）。
    database-schema-update: true
    ##  activiti7 默认不生成历史表信息 开启历史表
    db-history-used: true
    ## 记录历史等级 可配置的历史级别有none, activity, audit, full
    #none：不保存任何的历史数据，因此，在流程执行过程中，这是最高效的。
    #activity：级别高于none，保存流程实例与流程行为，其他数据不保存。
    #audit：除activity级别会保存的数据外，还会保存全部的流程任务及其属性。audit为history的默认值。
    #full：保存历史数据的最高级别，除了会保存audit级别的数据外，
    #       还会保存其他全部流程相关的细节数据，包括一些流程参数等。
    history-level: full
    #自动检查、部署流程定义文件
    check-process-definitions: false
    # asyncExecutorActivate是指activiti在流程引擎启动就激活AsyncExecutor,
    #    异步：true-开启（默认）、false-关闭
    async-executor-activate: true
    # 流程定义文件存放目录
    #process-definition-location-prefix:classpath:/bpmn/
    #流程定义文件格式
    #process-definition-location-suffixes:
    #  -**.bpmn
    ## 关闭SpringAutoDeployment
    deployment-mode: never-fail

# mybatis-plus设置
mybatis-plus:
  # 设置Mapper映射文件
  mapper-locations: classpath*:/mapper/*Mapper.xml
  type-aliases-package: com.hp.pojo
  configuration:
    # 自动他驼峰命名
    map-underscore-to-camel-case: true
# 打印日志（打印sql语句,就是mapper接口所在的包）
logging:
  level:
    com.hp.mapper: debug